### ISSUE TITLE
Upload firmware failed due to not enough memory!

### ISSUE THREAD

**Issue by NamkingWIN** [technik-gegg/SMuFF-Ifc#1]
I have a problem about the memory on the program partition. Please see the pic!
![67CAEDE7-387C-4E62-BF9C-D27C813D5843](https://user-images.githubusercontent.com/34998186/71572597-7aed5000-2b12-11ea-9c5c-a7f9dcedf631.jpeg)

**Comment by technik-gegg** [comment]
Seems that you don't have the latest version downloaded. I've changed the partition table recently.

**Comment by NamkingWIN** [comment]
I have updated from github and the new problems occur! 
![image](https://user-images.githubusercontent.com/34998186/71573472-a6723980-2b16-11ea-85b5-5bc97d1c8385.jpg)

**Comment by technik-gegg** [comment]
Please re-download platformio.ini and try again.

**Comment by NamkingWIN** [comment]
Upload successed! After  upload firmware and wifi connection established, but can not connect to the webserver from esp!

**Comment by technik-gegg** [comment]
Yes I know. Since one of the last framework updated the WiFi function has been rendered unusable for some reason (which I've already stated over on Thingiverse). I'll kick out the WiFi interface in the next release completely, so don't use it. 
If you want to check out the SMuFF-Ifc and get some status information, please use the Bluetooth connection.
