### ISSUE TITLE
Project discontinued ? :(

### ISSUE THREAD

**Issue by thbl** [technik-gegg/SMuFF-Ifc#3]
Hi @technik-gegg 
Just found your project and it looks awesome !  but then i saw the smuff home page and it says discontinued is that rigth ? :/

Also i see the scripts for Duet is 2 years old, do you know if there is any better way / other project that can work for the duet now days ? 
Thanks

**Comment by technik-gegg** [comment]
What's discontinued is V5. What's still available is V4.75 at Thingiverse or Cults3D. With the latest additions, V4.75 becomes almost V5 (or more V4.95 ;o). You still can build a SMuFF based on the "older" versions. The firmware you'll find in here (the SMuFF 2.0 Experimental branch) will work on either hardware. 
Please notice: The latest version of the firmware has got a lot of mods and updates, so the SMuFF-Ifc isn't really needed anymore (since it all happens on the SMuFF controller board, as long as you use a SKR E3-DIP for it).
The scripts haven't been updated because I'm still running my Duets on 2.x. Though, the latest firmware version is able to do the necessary steps for a tool change on it's own (that is, if you have the [Shared Stepper option](https://sites.google.com/view/the-smuff/work-in-progress?authuser=0#h.9t7lx3ge3qt3) running), so most stuff in the scripts isn't really needed anymore. 
However, I haven't fully tested this version on the Duet (still running the "old" version). Should work but might still need some tweaking of the firmware.
If you're interested in building one, drop me a message on [Discord](https://discord.com/invite/BzZ3rBf).

**Comment by thbl** [comment]
Thanks for your reply i will connect on discord ;D
